import './globals.css'
import type { Metadata } from 'next'
import Navbar from '../components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='fr' className='scroll-smooth'>
      <body>
        <header className='relative bg-white'>
          <Navbar />
          <h1 className='text-center text-primary-dark pt-80'>Hello Next.js</h1>
        </header>
        <main className='text-center'>{children}</main>
        <footer></footer>
      </body>
    </html>
  )
}
