import type { Metadata } from 'next'
import { getRecords } from '@/database/get-records'
import { Project } from '@/interfaces/Project'
import ProjectsNav from '@/components/project/ProjectsNav'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function Layout({
  children
}: {
  children: React.ReactNode
}) {
  const projects: Project[] = (await getRecords()) || []

  return (
    <>
      {children}
      <ProjectsNav projects={projects} />
    </>
  )
}
