import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import { getRecords } from '@/database/get-records'
import { Project } from '@/interfaces/Project'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function Layout({
  children
}: {
  children: React.ReactNode
}) {
  const projects: Project[] = (await getRecords()) || []

  return (
    <>
      <aside className='absolute left-10 top-[300px] z-20'>
        <nav>
          <ol>
            {projects.map(({ id, cover }) => {
              return (
                <li key={id} className='mb-12'>
                  <Link href={`/projects/${id}`}>
                    <Image
                      src={cover[0].thumbnails.large.url}
                      alt=''
                      width={cover[0].thumbnails.large.width}
                      height={cover[0].thumbnails.large.height}
                      className='h-24 w-24'
                    />
                  </Link>
                </li>
              )
            })}
          </ol>
        </nav>
      </aside>
      {children}
    </>
  )
}
