import { Suspense } from 'react'
import type { Metadata } from 'next'
import { getRecords } from '@/database/getRecords'
import { projectRecordType } from '@/database/airtable'
import { Project } from '@/interfaces/Project'
import ReactQueryProvider from '@/providers/ReactQueryProvider'
import ProjectsNav from '@/components/project/ProjectsNav'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function Layout({
  children
}: {
  children: React.ReactNode
}) {
  const projects: Project[] = await getRecords(projectRecordType)

  return (
    <div>
      {children}
      <Suspense fallback={<div>Loading ...</div>}>
        <ProjectsNav projects={projects} />
      </Suspense>
    </div>
  )
}
